name: Build Release
on:
  push:
    tags:
      - "*"
env:
  ProjectName: smartdns
  Owner: hmbsbige # ${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/${{ env.Owner }}/${{ env.ProjectName }}:${{ github.ref_name }}
            ghcr.io/${{ env.Owner }}/${{ env.ProjectName }}:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            URL=https://github.com/pymumu/smartdns/releases/download/Release${{ github.ref_name }}

      - uses: Chizkiyahu/delete-untagged-ghcr-action@v2
        with:
          token: ${{ secrets.CR_PAT }}
          repository: ${{ github.repository }}
          repository_owner: ${{ github.repository_owner }}
          untagged_only: true
          except_untagged_multiplatform: true
          owner_type: user
